apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  type: NodePort # Use LoadBalancer for cloud providers
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000 # Optional for NodePort
  selector:
    app: frontend
